version: "3"
services:
  app:
    image: monitchat/danubio-bot
    build:
      context: .
      dockerfile: ./deploy/docker/Dockerfile
    volumes:
      - /etc/hostname:/etc/hostname:ro
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@pgbouncer-danubio-bot/danubio_bot
      - DATABASE_URL_PGBOUNCER=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/$DB_NAME
      - GUNICORN_WORKERS=2
      - MONITCHAT_API_ACCESS_TOKEN=${MONITCHAT_API_ACCESS_TOKEN}
      - MONITCHAT_SENDER=${MONITCHAT_SENDER}
      - MONITCHAT_BASE_URL=${MONITCHAT_BASE_URL}
      - no_proxy='*'
    ports:
      - "5000:5000"
    depends_on:
      - pgbouncer-danubio-bot

  pgbouncer-danubio-bot:
    image: edoburu/pgbouncer:1.18.0
    container_name: pgbouncer-danubio-bot
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}
      - AUTH_TYPE=plain
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=10000
    ports:
      - "5434:5432"
